apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "platform" group to read resources in the platform namespace.
kind: ClusterRoleBinding
metadata:
  name: platform-reader
subjects:
- kind: Group
  name: platform # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-reader
  apiGroup: rbac.authorization.k8s.io